# Generated by Django 4.1.3 on 2022-11-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='isbn',
        ),
    ]
