# Generated by Django 4.1.3 on 2022-11-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_song_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='summary',
            new_name='description',
        ),
    ]
