# Generated by Django 4.1.3 on 2022-11-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_summary_song_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='author',
            new_name='artist',
        ),
    ]
