# Generated by Django 4.1.3 on 2022-11-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_songinstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songinstance',
            old_name='book',
            new_name='song',
        ),
    ]
