# Generated by Django 4.1.3 on 2022-11-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_book_songinstance_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songinstance',
            old_name='imprint',
            new_name='label',
        ),
    ]
